use_frameworks!

target 'MCheckSwift_Example' do
  pod 'MCheckSwift', :path => '../'
  pod 'SVProgressHUD'
  use_frameworks!
  
  target 'MCheckSwift_Tests' do
    inherit! :search_paths

    
  end
end
